name: Upload Website
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@67fbcbb121271f7775d2e7715933280b06314838 # ratchet:aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::053932140667:role/mongulu-github
          role-session-name: mtchoun-mouh-deployment
          aws-region: eu-central-1
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # ratchet:actions/checkout@main
      - name: Copy Site files
        run: |
          aws s3 sync html s3://www.mongulu.cm --delete
